version: "3"
services:
  postgres:
    image: "postgres:9.6"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: odk
      POSTGRES_PASSWORD: odk
      POSTGRES_DATABASE: odk
    restart: always
  mail:
    image: "itsissa/namshi-smtp:4.92-8.deb10u6"
    volumes:
      - ./files/dkim/config:/etc/exim4/_docker_additional_macros:ro
      - ./files/dkim/rsa.private:/etc/exim4/domain.key:ro
    environment:
      - MAILNAME=${DOMAIN}
    restart: always
  service:
    image: ghcr.io/mattelacchiato/service:latest
    depends_on:
      - secrets
      - postgres
      - mail
      - pyxform
      - enketo
    volumes:
      - ./volumes/secrets:/etc/secrets
      - /data/transfer:/data/transfer
      - ./files/service/config.json.template:/usr/share/odk/config.json.template
    environment:
      - DOMAIN
      - SYSADMIN_EMAIL
      - ENKETO_API_KEY
    command: [ "./wait-for-it.sh", "postgres:5432", "--", "./start-odk.sh" ]
    restart: always
    logging:
      driver: local
  nginx:
    image: ghcr.io/mattelacchiato/nginx:latest
    depends_on:
      - service
      - enketo
    environment:
      - SSL_TYPE=${SSL_TYPE:-letsencrypt}
      - DOMAIN=${DOMAIN}
      - CERTBOT_EMAIL=${SYSADMIN_EMAIL}
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 80 || exit 1" ]
    restart: always
    logging:
      driver: local
      options:
        max-file: "30"
  pyxform:
    image: 'ghcr.io/getodk/pyxform-http:v1.6.0'
    restart: always
  secrets:
    image: ghcr.io/mattelacchiato/secrets:latest
    volumes:
      - ./volumes/secrets:/etc/secrets
    command: './generate-secrets.sh'
  enketo:
    volumes:
      - ./volumes/secrets:/etc/secrets
    image: ghcr.io/mattelacchiato/enketo:latest
    restart: always
    depends_on:
      - secrets
      - enketo_redis_main
      - enketo_redis_cache
    environment:
      - DOMAIN
      - SUPPORT_EMAIL=${SYSADMIN_EMAIL}
  enketo_redis_main:
    image: redis:5
    volumes:
      - ./files/enketo/redis-enketo-main.conf:/usr/local/etc/redis/redis.conf:ro
      - ./volumes/redis/main:/data
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
    restart: always
  enketo_redis_cache:
    image: redis:5
    volumes:
      - ./files/enketo/redis-enketo-cache.conf:/usr/local/etc/redis/redis.conf:ro
      - ./volumes/redis/cache:/data
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
    restart: always
